### ISSUE TITLE
scripts directory not automatically created

### ISSUE THREAD

**Issue by LindsayHill** [zenoamaro/ansible-influxdb#1]
Using 0.11 to install influxdb on Ubuntu 14.04.

Playbook copies init script to /opt/influxdb/current/scripts - but that directory does not exist.

I edited tasks/configure.yml to add this in the 'Create InfluxDB directories' section:
    - "{{influxdb_instance_dir}}"
    - "{{influxdb_instance_dir}}/scripts"

Note also there is a slight inconsistency - the "influxdb_instance_dir" variable ends with "/", whereas other directory variables do not. This leads to the full path being expanded as /opt/influxdb/current//scripts

**Comment by zenoamaro** [comment]
v0.1.2 should correct every issue listed.

Should be in Galaxy soon. Give it a go!

**Comment by LindsayHill** [comment]
Thanks, looks good.
